"""empty message

Revision ID: 049dfe12f581
Revises: 24a0772a67f3
Create Date: 2016-04-15 20:05:16.273753

"""

# revision identifiers, used by Alembic.
revision = '049dfe12f581'
down_revision = '24a0772a67f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('source_sentece', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'source_sentece')
    ### end Alembic commands ###
