"""empty message

Revision ID: 24a0772a67f3
Revises: 3fc1977aa782
Create Date: 2016-04-15 18:37:07.649593

"""

# revision identifiers, used by Alembic.
revision = '24a0772a67f3'
down_revision = '3fc1977aa782'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('news_article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'news_article', ['news_article_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'news_article_id')
    ### end Alembic commands ###
