"""empty message

Revision ID: 3fc1977aa782
Revises: 7b99bdffef94
Create Date: 2016-04-15 18:31:08.527388

"""

# revision identifiers, used by Alembic.
revision = '3fc1977aa782'
down_revision = '7b99bdffef94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('article_text', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('good_question_votes', sa.Integer(), nullable=True),
    sa.Column('bad_question_votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('news_article')
    ### end Alembic commands ###
