"""empty message

Revision ID: 7b99bdffef94
Revises: None
Create Date: 2016-04-14 00:32:23.451306

"""

# revision identifiers, used by Alembic.
revision = '7b99bdffef94'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_generation_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('questions', postgresql.JSON(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_generation_request')
    ### end Alembic commands ###
