"""empty message

Revision ID: e8a551946b3e
Revises: 09ad3b11398d
Create Date: 2016-04-20 23:12:25.459578

"""

# revision identifiers, used by Alembic.
revision = 'e8a551946b3e'
down_revision = '09ad3b11398d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer_choice', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer_choice', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR())
    ### end Alembic commands ###
